
- hosts: vagrants
  tasks:
    - name: install some packages
      apt: name={{item}} state=present update_cache=yes
      become: yes
      with_items:
        - imagemagick
        - nodejs
        - openssl
        - libreadline6
        - libreadline6-dev
        - build-essential
        - git
        - curl
        - zlib1g-dev
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libxml2-dev
        - libxslt-dev
        - sqlite3
        - libsqlite3-dev
        - libmysqlclient-dev
        - libqt4-dev
        - libqtwebkit-dev
        - xvfb
        - g++
        - flex
        - bison
        - gperf
        - perl
        - libfontconfig1-dev
        - libicu-dev
        - libfreetype6
        - libssl-dev
        - libpng-dev
        - libjpeg-dev
        - python
        - libx11-dev
        - libxext-dev
        - unzip
        - mysql-server
        - fonts-mplus

    - name: copy rbenv.sh
      copy: src=rbenv.sh dest=~/rbenv.sh mode=0777
      become: no

    - name: copy bash_profile
      copy: src=bash_profile dest=~/.bash_profile mode=0775
      become: no

    - name: git checkout rbenv
      git: >
        repo=https://github.com/sstephenson/rbenv.git
        dest=~/.rbenv
      become: no

    - name: git checkout ruby-build
      git: >
        repo=https://github.com/sstephenson/ruby-build.git
        dest=~/.rbenv/plugins/ruby-build/
      become: no

    - name: chown rbenv dir
      file: path=~/.rbenv owner=vagrant state=directory recurse=yes
      become: no

    - name: ruby-build install
      shell: /home/vagrant/.rbenv/plugins/ruby-build/install.sh
      become: yes

    - name: set rbenv environment
      shell: ~/rbenv.sh
      become: no

    - name: make phantomjs
      git: >
        repo=git://github.com/ariya/phantomjs.git
        dest=~/phantomjs/
      become: no
    
    - name: git phantomjs checkout
      shell: git checkout 2.1.1 chdir=~/phantomjs
      become: no

    - name: phantomjs submodule init
      shell: git submodule init chdir=~/phantomjs
      become: no

    - name: phantomjs submodule update
      shell: git submodule update chdir=~/phantomjs
      become: no

    - name: build phantomjs
      shell: python build.py chdir=~/phantomjs
      become: no

    - name: get ngrok
      get_url: url=https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
                 dest=~/
      become: no

    - name: unzip ngrok
      shell: yes no | unzip ngrok-stable-linux-amd64.zip chdir=~/
      become: no

    - shell: echo "please sign up ngrok!! and ./ngrok authtoken your_key"
      become: no
