
- hosts: vagrants
  sudo: true
  user: vagrant
  tasks:
    - name: install some packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - imagemagick
        - nodejs
        - phantomjs
        - openssl
        - libreadline6
        - libreadline6-dev
        - build-essential
        - git
        - curl
        - zlib1g-dev
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libxml2-dev
        - libxslt-dev
        - sqlite3
        - libsqlite3-dev
        - libmysqlclient-dev
        - libqt4-dev
        - libqtwebkit-dev
        - xvfb
        - libqtwebkit-dev

    - name: install mysql packages
      apt: name={{item}} state=installed
      with_items:
        - mysql-server

    - name: Set ruby
      copy: src=rbenv.sh dest=/home/vagrant/rbenv.sh mode=0777
      sudo: no

    - copy: src=bash_profile dest=/home/vagrant/.bash_profile mode=0775
      sudo: no

    - git: >
        repo=https://github.com/sstephenson/rbenv.git
        dest=/home/vagrant/.rbenv
      sudo: no

    - git: >
        repo=https://github.com/sstephenson/ruby-build.git
        dest=/home/vagrant/.rbenv/plugins/ruby-build/
      sudo: no

    - file: path=/home/vagrant/.rbenv owner=vagrant state=directory recurse=yes
      sudo: no

    - shell: /home/vagrant/.rbenv/plugins/ruby-build/install.sh

    - shell: /home/vagrant/rbenv.sh
      sudo: no

    - shell: gem update
      sudo: no

    - shell: gem install bundler
      sudo: yes

#    - shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
#      sudo: no
#
#    - shell: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
#      sudo: no
#
#    - shell: echo 'test -r ~/.bashrc && . ~/.bashrc' >> ~/.bash_profile
#      sudo: no
# 
#    - shell: /home/vagrant/.rbenv/plugins/ruby-build/install.sh
#
#    - shell: /bin/bash -lc 'rbenv install 2.0.0-p247 && rbenv rehash && rbenv global 2.0.0-p247'
#      sudo: no
